apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusternodenets.platform.awx.im
spec:
  group: platform.awx.im
  names:
    kind: XClusterNodeNet
    plural: xclusternodenets
  claimNames:
    kind: ClusterNodeNet
    plural: clusternodenets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
              parameters:
                type: object
                properties:
                  cluster:
                    type: string
                  network:
                    type: string
                  subnetwork:
                    type: string
          status:
            type: object
            properties:
              gke:
                type: object
                properties:
                  project:
                    type: string
                  serviceAccount:
                    type: string
